services:
  # ============================
  # APPLICATION
  # ============================
  trade-service:
    image: ${SERVICE_IMAGE_NAME}:${SERVICE_VERSION}
    container_name: ${SERVICE_CONTAINER_NAME}
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "${SERVICE_PORT}:${SERVICE_PORT}"
    networks:
      - trade-platform
    volumes:
      - trade_service_data:/data

volumes:
      trade_service_data:

networks:
  trade-platform:
    external: true
