spring:
  application:
    name: trade-service
  main:
    banner-mode: off
    log-startup: false
    lazy-initialization: true

  profiles:
    active: ${SPRING_PROFILES_ACTIVE:local}

  devtools:
    restart:
      enabled: false

  # =========================
  # DATASOURCE
  # =========================
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      initialization-fail-timeout: 0

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true

  # =========================
  # KAFKA
  # =========================
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    listener:
      auto-startup: false
    consumer:
      group-id: trade-service
      auto-offset-reset: earliest
      enable-auto-commit: false
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      acks: all
      retries: 5
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  # =========================
  # REDIS
  # =========================
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

  # =========================
  # MAIL
  # =========================
  mail:
    host: ${SPRING_MAIL_HOST}
    port: ${SPRING_MAIL_PORT}
    protocol: smtp

# =========================
# SERVER
# =========================
server:
  port: ${SERVICE_PORT}

# =========================
# ACTUATOR
# =========================
management:
  endpoints:
    web:
      exposure:
        include: health,info

logging:
  level:
    root: WARN
    org.springframework: WARN
    org.hibernate: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
